### ISSUE TITLE
Provide database scripts instead of DB backup file

### ISSUE THREAD

**Issue by nbaua** [CodeHeight/Chamber#3]
Hi,

I just cam across your project which appears really nicely structured and well codded.
I intend to use the best practices followed by you and learn MVC along side.

However I am not able to put through the DB backup (I am using SQL 2014 Express) and I get the following error.

> The database was backed up on a server running version 12.00.5000. That version is incompatible with this server, which is running version 11.00.2100. Either restore the database on a server that supports the backup, or use a backup that is compatible with this server.
> RESTORE DATABASE is terminating abnormally.

Request you to provide DB creation and seed data (Both DDL and DML) scripts for the simplicity.

Thanks

**Comment by CodeHeight** [comment]
Script completed.

**Comment by nbaua** [comment]
Thanks a lot.
